version: "3.8"

services:
    jtl-shop:
        image: jtlsoftware/shop
        build: ./docker/web
        ports:
            - "80:80"
        volumes:
            - ./shop:/var/www/html
        depends_on:
            - "jtl-db"
        networks:
            - mynetwork

    jtl-db:
        image: mariadb:10.11
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - jtl_db:/var/lib/mysql
        networks:
            - mynetwork


    phpmyadmin:
        image: phpmyadmin:5.1.0-apache
        ports:
            - "8080:80"
        environment:
            PMA_HOST: jtl-db
        depends_on:
            - "jtl-db"
        networks:
            - mynetwork

networks:
  mynetwork:

volumes:
    jtl_db:
