version: "3.8"

services:
  jtl-shop:
    image: jtl-shop
    build:
      context: ./docker/web
      args:
        PHP_VERSION: "8.2.14"
        JTL_VERSION: "v5-2-4"
        TZ: Europe/Berlin
    ports:
      - "80:80"
    depends_on:
      - "jtl-db"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - jtl_shop:/var/www/html
      - "./src:/var/www/html/"

  jtl-db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "shop"
      MYSQL_PASSWORD: "shop"
      TZ: "Europe/Berlin"
      MYSQL_DATABASE: "jtl_shop"
    volumes:
      - jtl_db:/var/lib/mysql

  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"

volumes:
  jtl_db:
  jtl_shop:
